window.ZOUSEEKING_API_BASE_URL = window.ZOUSEEKING_API_BASE_URL || "";
window.ZOUSEEKING_SUPABASE_URL = window.ZOUSEEKING_SUPABASE_URL || "https://fnogxuytbabxmqousifh.supabase.co";
window.ZOUSEEKING_SUPABASE_ANON_KEY = window.ZOUSEEKING_SUPABASE_ANON_KEY || "";
